version: '3'

services:

  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    volumes:
      - "./ontology/:/ontology"
      - "./pipeline:/pipeline"
    command: bash -c 'dos2unix scripts/master_builder.sh && sh scripts/master_builder.sh'
    tty: true
    stdin_open: true