version: '3.1'

services:
  rxnav-db:
    image: mariadb:10.4
    restart: "no"
    expose:
    - "3306"
    ports:
    - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
    secrets:
    - mysql_webuser_secret
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: webuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_webuser_secret
  rxnav-web:
    build: tomcat
    restart: "no"
    ports:
    - "4000:8080"
    secrets:
    - mysql_webuser_secret
    depends_on:
    - rxnav-db
secrets:
  mysql_webuser_secret:
    file: ./mysql-secret.txt
